// Code generated by protoc-gen-go. DO NOT EDIT.
// source: click.proto

package stat_repository

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClickNewsRequest struct {
	ClickUuid            string               `protobuf:"bytes,1,opt,name=click_uuid,json=clickUuid,proto3" json:"click_uuid,omitempty"`
	ClientUuid           string               `protobuf:"bytes,2,opt,name=client_uuid,json=clientUuid,proto3" json:"client_uuid,omitempty"`
	Stream               int32                `protobuf:"varint,3,opt,name=stream,proto3" json:"stream,omitempty"`
	NewsId               int32                `protobuf:"varint,4,opt,name=news_id,json=newsId,proto3" json:"news_id,omitempty"`
	NewsCategoryId       int32                `protobuf:"varint,5,opt,name=news_category_id,json=newsCategoryId,proto3" json:"news_category_id,omitempty"`
	PositionId           int32                `protobuf:"varint,6,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	Service              int32                `protobuf:"varint,7,opt,name=service,proto3" json:"service,omitempty"`
	From                 string               `protobuf:"bytes,8,opt,name=from,proto3" json:"from,omitempty"`
	To                   string               `protobuf:"bytes,9,opt,name=to,proto3" json:"to,omitempty"`
	PageView             int32                `protobuf:"varint,10,opt,name=page_view,json=pageView,proto3" json:"page_view,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ClickNewsRequest) Reset()         { *m = ClickNewsRequest{} }
func (m *ClickNewsRequest) String() string { return proto.CompactTextString(m) }
func (*ClickNewsRequest) ProtoMessage()    {}
func (*ClickNewsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_764ede89b454d19e, []int{0}
}

func (m *ClickNewsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClickNewsRequest.Unmarshal(m, b)
}
func (m *ClickNewsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClickNewsRequest.Marshal(b, m, deterministic)
}
func (m *ClickNewsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClickNewsRequest.Merge(m, src)
}
func (m *ClickNewsRequest) XXX_Size() int {
	return xxx_messageInfo_ClickNewsRequest.Size(m)
}
func (m *ClickNewsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClickNewsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClickNewsRequest proto.InternalMessageInfo

func (m *ClickNewsRequest) GetClickUuid() string {
	if m != nil {
		return m.ClickUuid
	}
	return ""
}

func (m *ClickNewsRequest) GetClientUuid() string {
	if m != nil {
		return m.ClientUuid
	}
	return ""
}

func (m *ClickNewsRequest) GetStream() int32 {
	if m != nil {
		return m.Stream
	}
	return 0
}

func (m *ClickNewsRequest) GetNewsId() int32 {
	if m != nil {
		return m.NewsId
	}
	return 0
}

func (m *ClickNewsRequest) GetNewsCategoryId() int32 {
	if m != nil {
		return m.NewsCategoryId
	}
	return 0
}

func (m *ClickNewsRequest) GetPositionId() int32 {
	if m != nil {
		return m.PositionId
	}
	return 0
}

func (m *ClickNewsRequest) GetService() int32 {
	if m != nil {
		return m.Service
	}
	return 0
}

func (m *ClickNewsRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *ClickNewsRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *ClickNewsRequest) GetPageView() int32 {
	if m != nil {
		return m.PageView
	}
	return 0
}

func (m *ClickNewsRequest) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type ClickTeaserRequest struct {
	ClickUuid            string               `protobuf:"bytes,1,opt,name=click_uuid,json=clickUuid,proto3" json:"click_uuid,omitempty"`
	ClientUuid           string               `protobuf:"bytes,2,opt,name=client_uuid,json=clientUuid,proto3" json:"client_uuid,omitempty"`
	Stream               int32                `protobuf:"varint,3,opt,name=stream,proto3" json:"stream,omitempty"`
	TeaserId             int32                `protobuf:"varint,4,opt,name=teaser_id,json=teaserId,proto3" json:"teaser_id,omitempty"`
	NewsId               int32                `protobuf:"varint,5,opt,name=news_id,json=newsId,proto3" json:"news_id,omitempty"`
	PositionId           int32                `protobuf:"varint,6,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	Service              int32                `protobuf:"varint,7,opt,name=service,proto3" json:"service,omitempty"`
	TeaserCategoryId     int32                `protobuf:"varint,8,opt,name=teaser_category_id,json=teaserCategoryId,proto3" json:"teaser_category_id,omitempty"`
	NewsCategoryId       int32                `protobuf:"varint,9,opt,name=news_category_id,json=newsCategoryId,proto3" json:"news_category_id,omitempty"`
	From                 string               `protobuf:"bytes,10,opt,name=from,proto3" json:"from,omitempty"`
	To                   string               `protobuf:"bytes,11,opt,name=to,proto3" json:"to,omitempty"`
	PageView             int32                `protobuf:"varint,12,opt,name=page_view,json=pageView,proto3" json:"page_view,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ClickTeaserRequest) Reset()         { *m = ClickTeaserRequest{} }
func (m *ClickTeaserRequest) String() string { return proto.CompactTextString(m) }
func (*ClickTeaserRequest) ProtoMessage()    {}
func (*ClickTeaserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_764ede89b454d19e, []int{1}
}

func (m *ClickTeaserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClickTeaserRequest.Unmarshal(m, b)
}
func (m *ClickTeaserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClickTeaserRequest.Marshal(b, m, deterministic)
}
func (m *ClickTeaserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClickTeaserRequest.Merge(m, src)
}
func (m *ClickTeaserRequest) XXX_Size() int {
	return xxx_messageInfo_ClickTeaserRequest.Size(m)
}
func (m *ClickTeaserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClickTeaserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClickTeaserRequest proto.InternalMessageInfo

func (m *ClickTeaserRequest) GetClickUuid() string {
	if m != nil {
		return m.ClickUuid
	}
	return ""
}

func (m *ClickTeaserRequest) GetClientUuid() string {
	if m != nil {
		return m.ClientUuid
	}
	return ""
}

func (m *ClickTeaserRequest) GetStream() int32 {
	if m != nil {
		return m.Stream
	}
	return 0
}

func (m *ClickTeaserRequest) GetTeaserId() int32 {
	if m != nil {
		return m.TeaserId
	}
	return 0
}

func (m *ClickTeaserRequest) GetNewsId() int32 {
	if m != nil {
		return m.NewsId
	}
	return 0
}

func (m *ClickTeaserRequest) GetPositionId() int32 {
	if m != nil {
		return m.PositionId
	}
	return 0
}

func (m *ClickTeaserRequest) GetService() int32 {
	if m != nil {
		return m.Service
	}
	return 0
}

func (m *ClickTeaserRequest) GetTeaserCategoryId() int32 {
	if m != nil {
		return m.TeaserCategoryId
	}
	return 0
}

func (m *ClickTeaserRequest) GetNewsCategoryId() int32 {
	if m != nil {
		return m.NewsCategoryId
	}
	return 0
}

func (m *ClickTeaserRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *ClickTeaserRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *ClickTeaserRequest) GetPageView() int32 {
	if m != nil {
		return m.PageView
	}
	return 0
}

func (m *ClickTeaserRequest) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*ClickNewsRequest)(nil), "stat.repository.ClickNewsRequest")
	proto.RegisterType((*ClickTeaserRequest)(nil), "stat.repository.ClickTeaserRequest")
}

func init() { proto.RegisterFile("click.proto", fileDescriptor_764ede89b454d19e) }

var fileDescriptor_764ede89b454d19e = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x91, 0xc1, 0x8b, 0xd3, 0x40,
	0x14, 0xc6, 0x49, 0x76, 0xdb, 0x26, 0x2f, 0x52, 0xcb, 0x1c, 0x74, 0xd8, 0x45, 0xb6, 0xec, 0x29,
	0x07, 0xc9, 0x82, 0x9e, 0x3c, 0x4a, 0x4f, 0xb9, 0x78, 0x08, 0xd5, 0x6b, 0x98, 0x26, 0xaf, 0x61,
	0xb0, 0xe9, 0xc4, 0x99, 0x97, 0x86, 0xfe, 0x59, 0xfe, 0x4f, 0xfe, 0x21, 0x92, 0x97, 0x04, 0x2b,
	0x16, 0x41, 0x64, 0x6f, 0x79, 0xdf, 0xf7, 0xcd, 0xbc, 0xcc, 0xf7, 0x83, 0xa8, 0x38, 0xe8, 0xe2,
	0x6b, 0xd2, 0x58, 0x43, 0x46, 0xbc, 0x74, 0xa4, 0x28, 0xb1, 0xd8, 0x18, 0xa7, 0xc9, 0xd8, 0xf3,
	0xdd, 0x43, 0x65, 0x4c, 0x75, 0xc0, 0x27, 0xb6, 0x77, 0xed, 0xfe, 0x89, 0x74, 0x8d, 0x8e, 0x54,
	0xdd, 0x0c, 0x27, 0x1e, 0x7f, 0xf8, 0xb0, 0xda, 0xf4, 0x37, 0x7c, 0xc2, 0xce, 0x65, 0xf8, 0xad,
	0x45, 0x47, 0xe2, 0x0d, 0x00, 0xdf, 0x9a, 0xb7, 0xad, 0x2e, 0xa5, 0xb7, 0xf6, 0xe2, 0x30, 0x0b,
	0x59, 0xf9, 0xdc, 0xea, 0x52, 0x3c, 0xf0, 0x52, 0x3c, 0xd2, 0xe0, 0xfb, 0xec, 0xc3, 0x20, 0x71,
	0xe0, 0x15, 0xcc, 0x1d, 0x59, 0x54, 0xb5, 0xbc, 0x59, 0x7b, 0xf1, 0x2c, 0x1b, 0x27, 0xf1, 0x1a,
	0x16, 0x47, 0xec, 0x5c, 0xae, 0x4b, 0x79, 0x3b, 0x18, 0xfd, 0x98, 0x96, 0x22, 0x86, 0x15, 0x1b,
	0x85, 0x22, 0xac, 0x8c, 0x3d, 0xf7, 0x89, 0x19, 0x27, 0x96, 0xbd, 0xbe, 0x19, 0xe5, 0x94, 0x77,
	0xf3, 0xe3, 0xb4, 0x39, 0xf6, 0xa1, 0x39, 0x87, 0x60, 0x92, 0xd2, 0x52, 0x48, 0x58, 0x38, 0xb4,
	0x27, 0x5d, 0xa0, 0x5c, 0xb0, 0x39, 0x8d, 0x42, 0xc0, 0xed, 0xde, 0x9a, 0x5a, 0x06, 0xfc, 0xbf,
	0xfc, 0x2d, 0x96, 0xe0, 0x93, 0x91, 0x21, 0x2b, 0x3e, 0x19, 0x71, 0x0f, 0x61, 0xa3, 0x2a, 0xcc,
	0x4f, 0x1a, 0x3b, 0x09, 0x7c, 0x3e, 0xe8, 0x85, 0x2f, 0x1a, 0x3b, 0xf1, 0x01, 0xa0, 0xb0, 0xa8,
	0x08, 0xcb, 0x5c, 0x91, 0x8c, 0xd6, 0x5e, 0x1c, 0xbd, 0xbb, 0x4b, 0x86, 0x86, 0x93, 0xa9, 0xe1,
	0x64, 0x3b, 0x35, 0x9c, 0x85, 0x63, 0xfa, 0x23, 0x3d, 0x7e, 0xbf, 0x01, 0xc1, 0x35, 0x6f, 0x51,
	0x39, 0xb4, 0xcf, 0x5d, 0xf4, 0x3d, 0x84, 0xc4, 0x8b, 0x7e, 0x55, 0x1d, 0x0c, 0x42, 0x5a, 0x5e,
	0x52, 0x98, 0xfd, 0x46, 0xe1, 0x3f, 0xba, 0x7d, 0x0b, 0x62, 0x5c, 0x78, 0x89, 0x30, 0xe0, 0xd0,
	0x6a, 0x70, 0x2e, 0x20, 0x5e, 0xc3, 0x1d, 0x5e, 0xc5, 0x3d, 0x31, 0x83, 0x3f, 0x98, 0x45, 0xd7,
	0x99, 0xbd, 0xf8, 0x2b, 0xb3, 0xe5, 0x3f, 0x30, 0xdb, 0xcd, 0xd9, 0x7e, 0xff, 0x33, 0x00, 0x00,
	0xff, 0xff, 0xb2, 0x42, 0xa0, 0x22, 0x62, 0x03, 0x00, 0x00,
}
