// Code generated by protoc-gen-go. DO NOT EDIT.
// source: view.proto

package stat_repository

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ViewNewsRequest struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ClientUuid           string               `protobuf:"bytes,2,opt,name=client_uuid,json=clientUuid,proto3" json:"client_uuid,omitempty"`
	Service              int32                `protobuf:"varint,3,opt,name=service,proto3" json:"service,omitempty"`
	Stream               int32                `protobuf:"varint,4,opt,name=stream,proto3" json:"stream,omitempty"`
	PageView             int32                `protobuf:"varint,5,opt,name=page_view,json=pageView,proto3" json:"page_view,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Messenger            []*ViewNewsElements  `protobuf:"bytes,7,rep,name=messenger,proto3" json:"messenger,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ViewNewsRequest) Reset()         { *m = ViewNewsRequest{} }
func (m *ViewNewsRequest) String() string { return proto.CompactTextString(m) }
func (*ViewNewsRequest) ProtoMessage()    {}
func (*ViewNewsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10c1b2aca93c333f, []int{0}
}

func (m *ViewNewsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewNewsRequest.Unmarshal(m, b)
}
func (m *ViewNewsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewNewsRequest.Marshal(b, m, deterministic)
}
func (m *ViewNewsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewNewsRequest.Merge(m, src)
}
func (m *ViewNewsRequest) XXX_Size() int {
	return xxx_messageInfo_ViewNewsRequest.Size(m)
}
func (m *ViewNewsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewNewsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ViewNewsRequest proto.InternalMessageInfo

func (m *ViewNewsRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ViewNewsRequest) GetClientUuid() string {
	if m != nil {
		return m.ClientUuid
	}
	return ""
}

func (m *ViewNewsRequest) GetService() int32 {
	if m != nil {
		return m.Service
	}
	return 0
}

func (m *ViewNewsRequest) GetStream() int32 {
	if m != nil {
		return m.Stream
	}
	return 0
}

func (m *ViewNewsRequest) GetPageView() int32 {
	if m != nil {
		return m.PageView
	}
	return 0
}

func (m *ViewNewsRequest) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *ViewNewsRequest) GetMessenger() []*ViewNewsElements {
	if m != nil {
		return m.Messenger
	}
	return nil
}

type ViewNewsElements struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int32    `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type                 string   `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Login                string   `protobuf:"bytes,6,opt,name=login,proto3" json:"login,omitempty"`
	EditedUserId         int32    `protobuf:"varint,7,opt,name=edited_user_id,json=editedUserId,proto3" json:"edited_user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewNewsElements) Reset()         { *m = ViewNewsElements{} }
func (m *ViewNewsElements) String() string { return proto.CompactTextString(m) }
func (*ViewNewsElements) ProtoMessage()    {}
func (*ViewNewsElements) Descriptor() ([]byte, []int) {
	return fileDescriptor_10c1b2aca93c333f, []int{1}
}

func (m *ViewNewsElements) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewNewsElements.Unmarshal(m, b)
}
func (m *ViewNewsElements) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewNewsElements.Marshal(b, m, deterministic)
}
func (m *ViewNewsElements) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewNewsElements.Merge(m, src)
}
func (m *ViewNewsElements) XXX_Size() int {
	return xxx_messageInfo_ViewNewsElements.Size(m)
}
func (m *ViewNewsElements) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewNewsElements.DiscardUnknown(m)
}

var xxx_messageInfo_ViewNewsElements proto.InternalMessageInfo

func (m *ViewNewsElements) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ViewNewsElements) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ViewNewsElements) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ViewNewsElements) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *ViewNewsElements) GetEditedUserId() int32 {
	if m != nil {
		return m.EditedUserId
	}
	return 0
}

type ViewTeaserRequest struct {
	Uuid                 string                `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ClientUuid           string                `protobuf:"bytes,2,opt,name=client_uuid,json=clientUuid,proto3" json:"client_uuid,omitempty"`
	Service              int32                 `protobuf:"varint,3,opt,name=service,proto3" json:"service,omitempty"`
	Stream               int32                 `protobuf:"varint,4,opt,name=stream,proto3" json:"stream,omitempty"`
	NewsId               int32                 `protobuf:"varint,5,opt,name=news_id,json=newsId,proto3" json:"news_id,omitempty"`
	NewsCategoryId       int32                 `protobuf:"varint,6,opt,name=news_category_id,json=newsCategoryId,proto3" json:"news_category_id,omitempty"`
	PageView             int32                 `protobuf:"varint,7,opt,name=page_view,json=pageView,proto3" json:"page_view,omitempty"`
	CreatedAt            *timestamp.Timestamp  `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Messenger            []*ViewTeaserElements `protobuf:"bytes,9,rep,name=messenger,proto3" json:"messenger,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ViewTeaserRequest) Reset()         { *m = ViewTeaserRequest{} }
func (m *ViewTeaserRequest) String() string { return proto.CompactTextString(m) }
func (*ViewTeaserRequest) ProtoMessage()    {}
func (*ViewTeaserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10c1b2aca93c333f, []int{2}
}

func (m *ViewTeaserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewTeaserRequest.Unmarshal(m, b)
}
func (m *ViewTeaserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewTeaserRequest.Marshal(b, m, deterministic)
}
func (m *ViewTeaserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewTeaserRequest.Merge(m, src)
}
func (m *ViewTeaserRequest) XXX_Size() int {
	return xxx_messageInfo_ViewTeaserRequest.Size(m)
}
func (m *ViewTeaserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewTeaserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ViewTeaserRequest proto.InternalMessageInfo

func (m *ViewTeaserRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ViewTeaserRequest) GetClientUuid() string {
	if m != nil {
		return m.ClientUuid
	}
	return ""
}

func (m *ViewTeaserRequest) GetService() int32 {
	if m != nil {
		return m.Service
	}
	return 0
}

func (m *ViewTeaserRequest) GetStream() int32 {
	if m != nil {
		return m.Stream
	}
	return 0
}

func (m *ViewTeaserRequest) GetNewsId() int32 {
	if m != nil {
		return m.NewsId
	}
	return 0
}

func (m *ViewTeaserRequest) GetNewsCategoryId() int32 {
	if m != nil {
		return m.NewsCategoryId
	}
	return 0
}

func (m *ViewTeaserRequest) GetPageView() int32 {
	if m != nil {
		return m.PageView
	}
	return 0
}

func (m *ViewTeaserRequest) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *ViewTeaserRequest) GetMessenger() []*ViewTeaserElements {
	if m != nil {
		return m.Messenger
	}
	return nil
}

type ViewTeaserElements struct {
	TeaserId             int32    `protobuf:"varint,1,opt,name=teaser_id,json=teaserId,proto3" json:"teaser_id,omitempty"`
	TeaserCategoryId     int32    `protobuf:"varint,2,opt,name=teaser_category_id,json=teaserCategoryId,proto3" json:"teaser_category_id,omitempty"`
	PositionId           int32    `protobuf:"varint,3,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewTeaserElements) Reset()         { *m = ViewTeaserElements{} }
func (m *ViewTeaserElements) String() string { return proto.CompactTextString(m) }
func (*ViewTeaserElements) ProtoMessage()    {}
func (*ViewTeaserElements) Descriptor() ([]byte, []int) {
	return fileDescriptor_10c1b2aca93c333f, []int{3}
}

func (m *ViewTeaserElements) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewTeaserElements.Unmarshal(m, b)
}
func (m *ViewTeaserElements) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewTeaserElements.Marshal(b, m, deterministic)
}
func (m *ViewTeaserElements) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewTeaserElements.Merge(m, src)
}
func (m *ViewTeaserElements) XXX_Size() int {
	return xxx_messageInfo_ViewTeaserElements.Size(m)
}
func (m *ViewTeaserElements) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewTeaserElements.DiscardUnknown(m)
}

var xxx_messageInfo_ViewTeaserElements proto.InternalMessageInfo

func (m *ViewTeaserElements) GetTeaserId() int32 {
	if m != nil {
		return m.TeaserId
	}
	return 0
}

func (m *ViewTeaserElements) GetTeaserCategoryId() int32 {
	if m != nil {
		return m.TeaserCategoryId
	}
	return 0
}

func (m *ViewTeaserElements) GetPositionId() int32 {
	if m != nil {
		return m.PositionId
	}
	return 0
}

func init() {
	proto.RegisterType((*ViewNewsRequest)(nil), "stat.repository.ViewNewsRequest")
	proto.RegisterType((*ViewNewsElements)(nil), "stat.repository.ViewNewsElements")
	proto.RegisterType((*ViewTeaserRequest)(nil), "stat.repository.ViewTeaserRequest")
	proto.RegisterType((*ViewTeaserElements)(nil), "stat.repository.ViewTeaserElements")
}

func init() { proto.RegisterFile("view.proto", fileDescriptor_10c1b2aca93c333f) }

var fileDescriptor_10c1b2aca93c333f = []byte{
	// 450 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x51, 0xb1, 0x8e, 0xd3, 0x40,
	0x10, 0x95, 0x7d, 0x17, 0x3b, 0x9e, 0xa0, 0x5c, 0x58, 0x21, 0xce, 0x3a, 0x8a, 0x84, 0x40, 0xe1,
	0x02, 0xf9, 0xa4, 0xa3, 0xa2, 0x42, 0x27, 0x44, 0xe1, 0x86, 0xc2, 0xba, 0xa3, 0xb5, 0xf6, 0xb2,
	0x83, 0xb5, 0x52, 0xec, 0x35, 0xbb, 0xeb, 0x8b, 0xd2, 0xd1, 0x53, 0xf1, 0x77, 0x7c, 0x0e, 0xda,
	0x59, 0x1b, 0xc2, 0x11, 0x21, 0xd1, 0xd0, 0xed, 0xbc, 0xf7, 0x76, 0xf4, 0xde, 0x3c, 0x80, 0x7b,
	0x89, 0xbb, 0xbc, 0xd3, 0xca, 0x2a, 0x76, 0x66, 0x2c, 0xb7, 0xb9, 0xc6, 0x4e, 0x19, 0x69, 0x95,
	0xde, 0x5f, 0x2c, 0x6b, 0xa5, 0xea, 0x2d, 0x5e, 0x12, 0x7d, 0xd7, 0x7f, 0xba, 0xb4, 0xb2, 0x41,
	0x63, 0x79, 0xd3, 0xf9, 0x1f, 0xeb, 0x6f, 0x21, 0x9c, 0x7d, 0x94, 0xb8, 0xfb, 0x80, 0x3b, 0x53,
	0xe2, 0xe7, 0x1e, 0x8d, 0x65, 0x0c, 0x4e, 0xfb, 0x5e, 0x8a, 0x34, 0x58, 0x05, 0x59, 0x52, 0xd2,
	0x9b, 0x2d, 0x61, 0xb6, 0xd9, 0x4a, 0x6c, 0x6d, 0x45, 0x54, 0x48, 0x14, 0x78, 0xe8, 0xd6, 0x09,
	0x52, 0x88, 0x0d, 0xea, 0x7b, 0xb9, 0xc1, 0xf4, 0x64, 0x15, 0x64, 0x93, 0x72, 0x1c, 0xd9, 0x53,
	0x88, 0x8c, 0xd5, 0xc8, 0x9b, 0xf4, 0x94, 0x88, 0x61, 0x62, 0xcf, 0x20, 0xe9, 0x78, 0x8d, 0x95,
	0xf3, 0x9f, 0x4e, 0x88, 0x9a, 0x3a, 0xc0, 0xd9, 0x61, 0x6f, 0x00, 0x36, 0x1a, 0xb9, 0x45, 0x51,
	0x71, 0x9b, 0x46, 0xab, 0x20, 0x9b, 0x5d, 0x5d, 0xe4, 0x3e, 0x4d, 0x3e, 0xa6, 0xc9, 0x6f, 0xc6,
	0x34, 0x65, 0x32, 0xa8, 0xaf, 0x2d, 0x7b, 0x0b, 0x49, 0x83, 0xc6, 0x60, 0x5b, 0xa3, 0x4e, 0xe3,
	0xd5, 0x49, 0x36, 0xbb, 0x7a, 0x9e, 0x3f, 0x38, 0x4c, 0x3e, 0x66, 0x7e, 0xbf, 0xc5, 0x06, 0x5b,
	0x6b, 0xca, 0x5f, 0x7f, 0xd6, 0x5f, 0x03, 0x58, 0x3c, 0xe4, 0xd9, 0x1c, 0xc2, 0xe1, 0x24, 0x93,
	0x32, 0x94, 0x82, 0x9d, 0x43, 0xdc, 0x1b, 0xd4, 0x95, 0x14, 0x63, 0x2c, 0x37, 0x16, 0xc2, 0x5d,
	0xcf, 0xee, 0x3b, 0xa4, 0x44, 0x49, 0x49, 0x6f, 0xf6, 0x04, 0x26, 0x5b, 0x55, 0xcb, 0x96, 0x82,
	0x24, 0xa5, 0x1f, 0xd8, 0x4b, 0x98, 0xa3, 0x90, 0x2e, 0xe2, 0xb8, 0x29, 0xa6, 0x4d, 0x8f, 0x3c,
	0x7a, 0x4b, 0xfb, 0xd6, 0xdf, 0x43, 0x78, 0xec, 0xdc, 0xdc, 0x20, 0x37, 0xa8, 0xff, 0x73, 0x47,
	0xe7, 0x10, 0xb7, 0xb8, 0x33, 0xce, 0x9b, 0x6f, 0x28, 0x72, 0x63, 0x21, 0x58, 0x06, 0x0b, 0x22,
	0x36, 0xdc, 0x62, 0xad, 0xf4, 0xde, 0x29, 0x22, 0x52, 0xcc, 0x1d, 0xfe, 0x6e, 0x80, 0x0b, 0xf1,
	0x7b, 0xcd, 0xf1, 0x5f, 0x6b, 0x9e, 0xfe, 0x4b, 0xcd, 0xd7, 0x87, 0x35, 0x27, 0x54, 0xf3, 0x8b,
	0xa3, 0x35, 0xfb, 0xc3, 0x1d, 0x2b, 0xfa, 0x4b, 0x00, 0xec, 0x4f, 0x85, 0x73, 0x6c, 0x09, 0xa9,
	0x7e, 0x36, 0x3e, 0xf5, 0x40, 0x21, 0xd8, 0x2b, 0x60, 0x03, 0x79, 0x18, 0x3d, 0x24, 0xd5, 0xc2,
	0x33, 0x07, 0xe1, 0x97, 0x30, 0x23, 0x2f, 0x52, 0xb5, 0x4e, 0xe6, 0xaf, 0x0e, 0x23, 0x54, 0x88,
	0xbb, 0x88, 0x42, 0xbe, 0xfe, 0x11, 0x00, 0x00, 0xff, 0xff, 0xbb, 0xd2, 0x0f, 0x43, 0xc6, 0x03,
	0x00, 0x00,
}
